services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=jamc
      - POSTGRES_PASSWORD=jamc
      - POSTGRES_DB=jamc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jamc"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - jamc-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://jamc:jamc@db:5432/jamc?schema=public
      - SIMILARITY_API_URL=http://qa-service:8000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db: condition: service_healthy
      - qa-service: condition: service_healthy
    networks:
      - jamc-network

  qa-service:
    build:
      context: ./services/qa-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db: condition: service_healthy
    networks:
      - jamc-network

volumes:
  postgres_data:

networks:
  jamc-network:
    driver: bridge
