services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=jamc
      - POSTGRES_PASSWORD=jamc
      - POSTGRES_DB=jamc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jamc"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Adminer for database management (development only)
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:

# For development:
# docker compose up -d
#
# For production:
# docker compose up -d
#
# Environment variables can be set in a .env file or passed via command line:
# TARGET=runner NODE_ENV=production COMMAND="node server.js" docker compose --profile prod up -d 