name: Lint

on:
  push:
    branches: [ "main" ]
    paths: [ "**/*.ts", "**/*.tsx", "package.json", "pnpm-lock.yaml" ]
  pull_request:
    paths: [ "**/*.ts", "**/*.tsx", "package.json", "pnpm-lock.yaml" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run ESLint
        run: pnpm run lint 
